syncfusion-content/asp.netmvc-docs

aspnetmvc/DropDownList/HowTo.md
aspnetmvc/Grid/Hierarchy-Grid.md
aspnetmvc/Grid/Row.md

Worked on Bing report issues, merge these changes.
Regards,
Gowthaman

SEO-1973_Site_Audit_Issues

---

aspnetmvc/DataManager/IEnumerable-IQueryable.md

Worked on Site Audit Bing report issues, merge these changes.
Regards,
Gowthaman

SEO-2050_Site_Audit_Issues

---

aspnetmvc/Combobox/how-to.md
aspnetmvc/TimePicker/Localization.md
aspnetmvc/TimePicker/TimePicker-Customization.md
aspnetmvc/TreeGrid/Data-Binding.md
aspnetmvc/TreeGrid/Rows.md

Worked on Site Audit issues, so merge these changes,
Regards,
Gowthaman

SEO-2423_Site_Audit_Issues

---

aspnetmvc/Combobox/accessibility.md
aspnetmvc/TimePicker/Time-Format.md
aspnetmvc/TreeGrid/Sorting.md

Worked on site audit issues, merge these changes,
Regards,
Gowthaman

SEO-2513_Site_Audit_Issues

---

aspnetmvc/Grid/Data-Adaptors.md
aspnetmvc/Grid/Data-Binding.md
aspnetmvc/RichTextEditor/Image-and-File-browser.md

Please find changes made on ASP.NET MVC md file.
Regards,
Scholar.

SEO-2489 ASP.NET MVC changes

---

aspnetmvc/getting-started.md

Please review the changes for ASP.NET MVC controls.
Regards,
Sharly A.

SEO-3267 - ASP.NET MVC controls Permanent redirect

---

aspnetmvc/ColorPicker/Knockout-Binding.md
aspnetmvc/Gantt/Customizations.md
aspnetmvc/PivotGrid/Format-String.md
aspnetmvc/TreeGrid/Filtering.md

Worked on Bing report issues, so merge these changes
Regards,
Gowthaman

SEO-3615-bing-issues

---

aspnetmvc/DatePicker/Getting-Started.md

Have changed redirect links.
Regards,
Yvone.

SEO-171761 ASP.NET MVC Page with redirect links

---

aspnetmvc/Chart/Getting-Started.md

Hi @MallikaRK  ,
Have changed the redirect links, Please review.
Thanks.
Regards,
Edith.

SEO-172121 asp net mvc controls

---

aspnetmvc/Grid/Cell.md
aspnetmvc/Grid/Columns.md
aspnetmvc/Grid/Data-Adaptors.md
aspnetmvc/Grid/Data-Binding.md
aspnetmvc/Grid/Editing.md
aspnetmvc/Grid/Enable-Persistence.md
aspnetmvc/Grid/Exporting.md
aspnetmvc/Grid/Getting-Started.md
aspnetmvc/Grid/Grouping.md
aspnetmvc/Grid/How-to.md
aspnetmvc/Grid/Localization.md
aspnetmvc/Grid/Print-Grid.md
aspnetmvc/Grid/Style-and-Appearance.md
aspnetmvc/Grid/Summary.md
aspnetmvc/HeatMap/Getting-Started.md
aspnetmvc/Kanban/Column.md
aspnetmvc/Kanban/Editing.md
aspnetmvc/Kanban/Filtering.md
aspnetmvc/Kanban/Getting-Started.md
aspnetmvc/Kanban/Overview.md
aspnetmvc/Kanban/Styling.md
aspnetmvc/Licensing/how-to-generate.md
aspnetmvc/Licensing/licensing-errors.md
aspnetmvc/Licensing/overview.md
aspnetmvc/LinearGauge/Getting-Started.md
aspnetmvc/ListBox/Keyboard-interaction.md
aspnetmvc/ListView/Data-Binding.md
aspnetmvc/ListView/Getting-Started.md
aspnetmvc/installation/Installation-Errors.md

Worked on redirection fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-aspnet-mvc-redirection-fixes-3

---

aspnetmvc/Maps/Getting-Started.md
aspnetmvc/Maps/Overview.md
aspnetmvc/Maps/Populate-Data.md
aspnetmvc/MaskEdit/Behavior-Settings.md
aspnetmvc/Menu/Data-binding.md
aspnetmvc/Menu/Getting-Started.md
aspnetmvc/Menu/Responsive-Layout.md
aspnetmvc/NavigationDrawer/Getting-Started.md
aspnetmvc/NumericTextBox/Keyboard-Interaction.md
aspnetmvc/NumericTextBox/Localization-Support.md
aspnetmvc/PdfViewer/GettingStarted.md
aspnetmvc/PercentageTextBox/Keyboard-Interaction.md
aspnetmvc/PercentageTextBox/Localization-Support.md
aspnetmvc/PivotChart/OLAP-Getting-Started.md
aspnetmvc/PivotChart/Relational-Getting-Started.md
aspnetmvc/PivotClient/OLAP-Getting-Started.md
aspnetmvc/PivotClient/Relational-Getting-Started.md
aspnetmvc/PivotGauge/OLAP-Getting-Started.md
aspnetmvc/PivotGauge/Relational-Connectivity.md
aspnetmvc/PivotGauge/Relational-Getting-Started.md
aspnetmvc/PivotGrid/OLAP-Getting-Started.md
aspnetmvc/PivotGrid/Relational-Getting-Started.md
aspnetmvc/PivotTreeMap/Getting-Started.md
aspnetmvc/ProgressBar/Getting-Started.md
aspnetmvc/ProgressBar/Overview.md

Worked on redirection fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-aspnet-mvc-redirection-fixes-4

---

aspnetmvc/Diagram/Automatic-Layout.md
aspnetmvc/Grid/Data-Binding.md
aspnetmvc/Grid/Style-and-Appearance.md
aspnetmvc/Schedule/Data-binding.md

Have changed ASP.NET MVC Page with Redirect.
Regards,
Yvone.

SEO-174775 ASP.NET MVC Page with Redirect

---

aspnetmvc/Grid/How-to.md
aspnetmvc/Tab/Getting-Started.md
aspnetmvc/UploadBox/File-Size.md

Have changed ASP.NET MVC Page with Redirect UG.
Regards,
Yvone.

SEO-175659 ASPNETMVC Page with Redirect

---

aspnetmvc/DatePicker/How-To.md
aspnetmvc/installation/offline-installer/how-to-install.md

Have changed ASP.NET MVC Page with Redirect UG.
Regards,
Yvone.

SEO-175659 MVC Page with Redirect

---

aspnetmvc/Grid/Print-Grid.md

Hello,
Worked on the links with redirects.
Regards,
Beryl.

SEO-175653-MVC-Pages-With-Redirects

---

aspnetmvc/DatePicker/Getting-Started.md

Hello,
I have worked on links with redirects.
Regards,
Beryl.

SEO-178943-Redirect-Links-MVC

---

aspnetmvc/Chart/3D-Chart.md

Hi @MallikaRK ,
Please review the redirect link changes made
Thanks.
Regards,
Edith.

SEO-178901-mvc-page-with-redirect

---

aspnetmvc/Chart/Chart-Types.md
aspnetmvc/Grid/Style-and-Appearance.md

Have worked on Page with Redirect links.
Regards,
Yvone.

SEO-178115 ASP.NET MVC Redirect

---

aspnetmvc/Chart/Data-Markers.md
aspnetmvc/Chart/Working-with-Data.md

Hi @MallikaRK ,
Kindly review the PR changes.
Regards,
Edith.

SEO-180844-mvc-page-with-redirect

---

aspnetmvc/Rating/Overview.md

Hi @Yvone-Atieno,
|Title|Description|
|--|--|
|Category|Title too long/short link |
|Hotfix PR|https://github.com/syncfusion-content/asp.netmvc-docs/pull/447|
|Task||
|Content Ticket||
|UX Ticket||
|Changes made|Reason for changes|
|--|--|
|Modify meta elements|For meta alignment with proper character count|
Regards,
Edith.

SEO-187452-mvc-Title-too-long/short
