aspnetmvc/Chart/Appearance.md
aspnetmvc/DataManager/Data-Adaptors.md
aspnetmvc/Spreadsheet/Scrolling.md

Worked on Site Audit Issues, merge these changes.
Regards,
Gowthaman

SEO-2008_Site_Audit_Issues

---

aspnetmvc/DataManager/IEnumerable-IQueryable.md
aspnetmvc/Diagram/Data-Binding.md
aspnetmvc/Diagram/Getting-Started.md

Worked on Site Audit Bing report issues, merge these changes.
Regards,
Gowthaman

SEO-2111_Site_Audit_Issues

---

aspnetmvc/Combobox/localization.md
aspnetmvc/Grid/Exporting.md
aspnetmvc/Grid/Localization.md
aspnetmvc/Grid/Toolbar.md
aspnetmvc/TimePicker/Getting-Started.md

Worked on site audit issues, merge these changes.
Regards,
Gowthaman

SEO-2344_Site_Audit_Issues

---

aspnetmvc/Licensing/how-to-generate.md
aspnetmvc/Licensing/licensing-errors.md
aspnetmvc/Licensing/licensing-faq/how-to-upgrade-from-trial-version-after-purchasing-a-license.md
aspnetmvc/Licensing/licensing-faq/registering-syncfusion-account-for-nuget-org-user.md
aspnetmvc/Licensing/overview.md
aspnetmvc/Upgrade/how-to-upgrade.md
aspnetmvc/installation/Installation-Errors.md
aspnetmvc/installation/offline-installer/how-to-download.md
aspnetmvc/installation/web-installer/how-to-download.md

IN-18200-UG-Documentation-aspnetmvc-hotfix

---

aspnetmvc/Combobox/getting-started.md
aspnetmvc/Grid/Grouping.md
aspnetmvc/Grid/Stackedheader.md
aspnetmvc/TimePicker/Keyboard-Interaction.md

Worked on Site Audit Issues, merge these changes.
Regards,
Gowthaman

SEO-2370_Site_Audit_Issues

---

aspnetmvc/ComboBox/sorting.md
aspnetmvc/TreeGrid/Getting-Started.md
aspnetmvc/TreeView/Getting-Started.md

Worked on site audit issues, so merge these changes,
Regards,
Gowthaman

SEO-2423_Site_Audit_Issues

---

aspnetmvc/Combobox/accessibility.md
aspnetmvc/TimePicker/Time-Format.md
aspnetmvc/TreeGrid/Sorting.md

Worked on site audit issues, merge these changes,
Regards,
Gowthaman

SEO-2475_Site_Audit_Issues

---

aspnetmvc/Grid/How-to.md

Please review the image alt text changes for ASP.NET MVC Grid.
Regards,
Sharly A.

SEO-2488 - ASP.NET MVC Grid image alt text

---

aspnetmvc/Chart/Getting-Started.md

|Task Category| Pages With Redirect - Search console|
|:--|:--|
|Issue count| Help site links - 1000 |
|Fixed Count| Help site links - 1 |
|Analysis| Inspecting the links and found referring pages |
|Solution| replaced the exact URL instead of old URL |
|Hotfix PR| https://github.com/syncfusion-content/asp.netmvc-docs/pull/222 | 
|Task link|https://syncfusion.atlassian.net/browse/SEO-2684|
|Excel| N/A |
Regards,
Gowthaman

SEO-2684-Coverage-Page-With-Redirect-UG

---

aspnetmvc/Introduction.md

Please review the changes for Windows Forms HTTP to HTTPS.
Regards,
Yvone.

SEO-2706 ASP.NET MVC HTTP To HTTPS

---

aspnetmvc/Button/Button-Type.md
aspnetmvc/Captcha/Getting-Started.md
aspnetmvc/Grid/How-to.md
aspnetmvc/ListView/Getting-Started.md
aspnetmvc/RadialMenu/TemplateSupport.md
aspnetmvc/WaitingPopup/Overview.md

Please review the changes for ASP.NET MVC Desc too long short.
Regards,
Yvone.

SEO-3147 ASP.NET MVC Desc too long short

---

aspnetmvc/Chart/Axis.md
aspnetmvc/DropDownList/Getting-Started.md

Please review page with redirect changes for ASP.NET MVC.
Regards,
Sharly A.

SEO-3222- ASP.NET MVC controls page with redirect

---

aspnetmvc/Button/Button-Type.md
aspnetmvc/Grid/Getting-Started.md
aspnetmvc/Tooltip/HowTo.md

Hi @Aishwarya-Ganesan 
Added missing image alt text.
Regards,
Beryl

SEO-3151-MVC-Image-Alt-Text

---

aspnetmvc/DataManager/Query.md
aspnetmvc/Grid/Exporting.md
aspnetmvc/Grid/Scrolling.md

Please review the changes for Page with redirect in ASP.NET MVC.
Regards,
Yvone.

SEO-3239 ASP.NET MVC Page with redirect

---

aspnetmvc/Captcha/Overview.md
aspnetmvc/PdfViewer/Toolbar-Customization.md

Worked on bing report issues, so merge these changes
Regards,
Gowthaman

SEO-3261-bing-report-issues

---

aspnetmvc/Licensing/how-to-generate.md

Added redirect links for file format.
Regards,
Sharly A.

SEO-3446 - ASP.NET MVC redirection link added

---

aspnetmvc/Captcha/Overview.md

Worked on bing report issues, so merge these changes
Regards,
Gowthaman

SEO-3439-semrush-report-issues

---

aspnetmvc/Autocomplete/How-to.md
aspnetmvc/Button/Overview.md
aspnetmvc/Checkbox/Easy-customization.md
aspnetmvc/DateRangePicker/getting-started.md
aspnetmvc/Gantt/Columns.md
aspnetmvc/Gantt/How-to/Change-Splitter-position.md
aspnetmvc/LinearGauge/Labels.md
aspnetmvc/NumericTextBox/Overview.md
aspnetmvc/RadioButton/Easy-Customization.md
aspnetmvc/ReportViewer/Report-Parameters.md
aspnetmvc/TreeView/How-To.md

Have changed title, description, H1 and named images.
Regards,
Yvone.

SEO-3569 ASP.NET MVC Site Audit Issues

---

aspnetmvc/ListBox/Getting-Started.md
aspnetmvc/Maps/Map-Providers.md

Hi,
I have worked on the pages with redirects,
Regards,
Beryl

SEO-171356-Pages-With-Redirects-MVC

---

aspnetmvc/RadialMenu/dimension.md

Please review the changes for missing H1 below.
Regards,
Sharly A.

SEO-171911 - ASP.NET MVC Control Missing H1

---

aspnetmvc/ListView/Data-Binding.md
aspnetmvc/NumericTextBox/Getting-Started.md

Hi @gowthamanthavasiyappan ,
Have changed title, H1 and description for ASP.NET MVC.
Regards,
Yvone.

SEO-172157 ASP.NET MVC Desc too long short.

---

aspnetmvc/Introduction.md

Please review ASP.NET MVC Introduction
Regards,
Sharly A.

SEO-172146 - ASP.NET MVC Introduction

---

aspnetmvc/Button/Easy-Customization.md
aspnetmvc/Button/Getting-Started.md
aspnetmvc/Captcha/Enabling-Validation.md
aspnetmvc/Gantt/Localization.md
aspnetmvc/Grid/Style-and-Appearance.md
aspnetmvc/ListView/Data-Binding.md
aspnetmvc/NumericTextBox/Getting-Started.md
aspnetmvc/TreeGrid/Selection.md

Hi @MallikaRK,
Worked on description too long / short.
Regards,
Sharly A.

SEO-172159 - ASP.NET MVC description too ling / short

---

aspnetmvc/DataManager/Data-Binding.md
aspnetmvc/DataManager/corsdatafetching.md
aspnetmvc/DatePicker/Behavior-Settings.md
aspnetmvc/DatePicker/Customization.md
aspnetmvc/DatePicker/Display-Format.md
aspnetmvc/DatePicker/Getting-Started.md
aspnetmvc/DatePicker/Globalization.md
aspnetmvc/DatePicker/How-To.md
aspnetmvc/DatePicker/Miscellaneous.md
aspnetmvc/DatePicker/State-Persistence.md
aspnetmvc/DatePicker/Validation.md
aspnetmvc/DateRangePicker/globalization.md
aspnetmvc/DateTimePicker/Localization.md
aspnetmvc/Diagram/Getting-Started.md
aspnetmvc/Dialog/Getting-Started.md
aspnetmvc/DigitalGauge/Getting-Started.md
aspnetmvc/DropDownList/Accessibility.md
aspnetmvc/DropDownList/Customization.md
aspnetmvc/DropDownList/DataBinding.md
aspnetmvc/DropDownList/DropDownList-dependencies.md
aspnetmvc/DropDownList/Functionalities.md
aspnetmvc/DropDownList/Rendering-Mode.md
aspnetmvc/DropDownList/TemplateSupport.md
aspnetmvc/DropDownList/Validation.md

Worked on redirection fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-aspnet-mvc-redirection-fixes-1

---

aspnetmvc/Accessibility.md
aspnetmvc/Configuration-and-Deployment.md
aspnetmvc/Dependencies.md
aspnetmvc/Introduction.md
aspnetmvc/RadialMenu/Getting-Started.md
aspnetmvc/RadialMenu/radialmenu-dependencies.md
aspnetmvc/RadialSlider/Getting-Started.md
aspnetmvc/RadialSlider/radialslider-dependencies.md
aspnetmvc/RadioButton/Getting-Started.md
aspnetmvc/RangeNavigator/User-Interactions.md
aspnetmvc/Rating/Getting-Started.md
aspnetmvc/Release-notes/v13.4.0.53.md
aspnetmvc/Release-notes/v14.1.0.41.md
aspnetmvc/Release-notes/v14.3.0.49.md
aspnetmvc/Release-notes/v14.4.0.15.md
aspnetmvc/Release-notes/v16.1.0.24.md
aspnetmvc/Release-notes/v16.3.0.21.md
aspnetmvc/Release-notes/v16.4.0.40.md
aspnetmvc/Release-notes/v16.4.0.42.md
aspnetmvc/Release-notes/v20.1.0.47.md
aspnetmvc/Unobtrusive.md
aspnetmvc/getting-started-vs-2019.md
aspnetmvc/getting-started.md

Worked on redirection fixes, so merge these changes,
Regards,
Gowthaman

SEO-172685-aspnet-mvc-redirection-fixes-5

---

aspnetmvc/DropDownList/LoadOnDemand.md
aspnetmvc/RadialMenu/dimension.md

Worked on missing H1. Kindly review.
Regard
Dickson J

SEO-172168-ASP.NETMVC-Demand and Dimention control missing H1

---

aspnetmvc/Diagram/Connector.md

Have changed ASP.NET MVC Page with Redirect links, please review.
Regards,
Yvone.

SEO-174775 ASP.NET MVC Page with Redirect

---

aspnetmvc/Diagram/Data-Binding.md
aspnetmvc/Ribbon/Appearance-and-Styling.md
aspnetmvc/UploadBox/Getting-Started.md
aspnetmvc/WaitingPopup/Overview.md

Have worked on changing Page with Redirect links.
Regards,
Yvone.

SEO-175190 ASP.NET MVC Redirect

---

aspnetmvc-toc.html

Hi all,
- With this PR, we have added DocIO & Presentation controls in ASP.NET MVC EJ1 platform UG.
Regards,
Dharanitharan A

ES-846833-Add DocIO & Presentation controls in ASP.NET MVC EJ1 platform UG-hotfix

---

aspnetmvc/DataManager/Antiforgery.md

Hello,
I have worked on the missing H1
Regards,
Beryl.

SEO-176113-MVC-Missing-H1

---

aspnetmvc/Diagram/Gridlines.md

Have changed Page with Redirect links.
Regards,
Yvone.

SEO-178567 ASP.NET MVC Page Redirect

---

aspnetmvc/Chart/Chart-Series.md

Hello,
I have worked on links with redirects.
Regards,
Beryl.

SEO-178943-Redirect-Links-MVC1

---

aspnetmvc/Schedule/Data-binding.md

Hi @MallikaRK ,
Please review the redirect link changes made
Thanks.
Regards,
Edith.

SEO-178901-mvc-ug-page-with-redirect-links

---

aspnetmvc/DateTimePicker/Overview.md
aspnetmvc/ProgressBar/Getting-Started.md

Hi @MallikaRK,
Work on description too long/short.
Regards,
Sharly A.

SEO-180850-ASP.NET-MVC-Overview
